#!/bin/sh

cd `dirname $0`
if [ ! -d tmp ]; then mkdir tmp; fi
rm -f smvflatten
ln -s ../../../bin/smvflatten .
. ../../../config.sh
[ "$cmu_smv" ] || exit 1
cd tmp

$cmu_smv -r ../in 1> smv1.log 2> smv1.err || exit 1
../smvflatten -mangle $* ../in 1>in-flat 2>err || exit 1
$cmu_smv -r in-flat 1> smv2.log 2> smv2.err || exit 1

line=`fgrep 'reachable states:' smv1.log`
reachable=`echo $line | sed -e 's,.*: \([0-9]*\) .*,\1,'`
[ "$reachable" = 12 ] || exit 1

line=`fgrep 'reachable states:' smv2.log`
reachable=`echo $line | sed -e 's,.*: \([0-9]*\) .*,\1,'`
#
# four 1 bit oracle + 3 times running gives a factor of 48 and 48 * 12 = 576
#
[ "$reachable" = 576 ] || exit 1

for log in smv1.log smv2.log
do
  [ "`fgrep 'is true' $log|wc -l|sed -e 's,[ 	],,g'`" = 0 ] || exit 1
  [ "`fgrep 'is false' $log|wc -l|sed -e 's,[ 	],,g'`" = 1 ] || exit 1
done

exit 0
