#!/bin/sh

cd `dirname $0`
if [ ! -d tmp ]; then mkdir tmp; fi
rm -f smvflatten
ln -s ../../../bin/smvflatten .
cd tmp

../smvflatten $* -v9 ../in 1>log 2>err || exit 1
[ "`fgrep '2 unused' err`" ] || exit 1
exit 0
