#!/bin/sh

cd `dirname $0`
if [ ! -d tmp ]; then mkdir tmp; fi
rm -f smvflatten
ln -s ../../../bin/smvflatten .
cd tmp

../smvflatten $* -e ../in 1>log 2>err || exit 1
cmp -s ../out log || exit 1
exit 0
